language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

# Works around an issue in Travis, see
# https://github.com/travis-ci/travis-ci/issues/5227.
#
# The fix below is due to @BanzaiMan, see
# https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
